name: Release Plugin Beta

on:
  push:
    tags:
      - "*b"

env:
  PLUGIN_NAME: obsidian-advanced-html-export # Plugin ID from manifest.json

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22.x"
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Build
        id: build
        run: |
          pnpm install
          pnpm build
          mkdir ${{ env.PLUGIN_NAME }}
          cp dist/main.js dist/manifest.json dist/styles.css ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}
          ls
          echo "tag_name=$(git tag --sort version:refname | tail -n 1)" >> "$GITHUB_OUTPUT"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            dist/main.js
            dist/styles.css
            dist/manifest.json